### ISSUE TITLE
Add internationalization library

### ISSUE THREAD

**Issue by lucasecdb** [lucasecdb/cramkle#5]
translated views:

- [x] Landing page (#40)
- [x] Login page (#40)
- [x] Register page (#40)
- [x] Home page (#40)
- [x] Decks section (#40)
- [x] Models section (#40)
- [x] Model page (#40)
- [x] Deck page (#40)
- [x] Add deck page (#40)
- [x] Add model page (#40)
- [x] App drawer (#40)

other functionalities:

- [x] auto detection in server side (#41)
- [x] change language in client side (#42)
